### ISSUE TITLE
Weird JSONArray behavior

### ISSUE THREAD

**Issue by solomax** [tdunning/open-json#5]
the following pseudo code
```
	JSONArray jsonArray = new JSONArray();
	jsonArray.put(Arrays.asList(1, 2, 3, 4, 5));
	return jsonArray.toString();
```
produces weird JSON string: ["[1, 2, 3, 5]"]
I believe it should be: [[1, 2, 3, 5]]

Will write test, and try to provide PR ASAP

**Comment by tdunning** [comment]
Thanks.

**Comment by solomax** [comment]
Seems to be false alert caused by outdated Maven cache :(
Sorry for the noise
