### ISSUE TITLE
Java 6 compatibility for JSONObject

### ISSUE THREAD

**Issue by klopfdreh** [tdunning/open-json#6]
Hi,

as I saw in code changes for https://github.com/apache/wicket/pull/194 there are issues with the call in the following line https://github.com/tdunning/open-json/blob/master/src/main/java/org/json/JSONObject.java#L115

My suggestion is to replace the code line:
```java
return Objects.hashCode(null);
```

with
```java
return 0;
```

because it is simply the same as you can see in Arrays.hashCode(null) called by Objects.hashCode(null);
```java
        if (a == null)
            return 0;
```

this issue occurs, because Objects is not available in Java 6.

**Comment by tdunning** [comment]
Great suggestion!

I am swamped just now. Can you make a pull request so that we can get this
into the next release?



On Thu, Dec 8, 2016 at 3:02 AM, Tobias Soloschenko <notifications@github.com
